name: st3
channels:
  - conda-forge
dependencies:
  - conda-ecosystem-user-package-isolation
  - python  >=3.10

  - loguru
  - networkx
  - psutil
  - psycopg
  - requests-ratelimiter
  - xdg

  # dev
  - black
  - isort
  - pytest
